language: objective-c
osx_image: xcode611

before_script:
- gem install xcpretty -N

# Set up mock API server
- cd ..
- git clone https://github.com/minhtule/SimpleMockServer
- cd SimpleMockServer
- npm install
- node app.js &
- cd ../SimpleiOSTest

script:
- set -o pipefail
- xcodebuild -project SimpleTest.xcodeproj -scheme "SimpleTest" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO test | xcpretty -c