language: objective-c
osx_image: xcode611
script:
- xcodebuild -project SimpleTest.xcodeproj -scheme "SimpleTest" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO test